version: 2
updates:

  # Check for updates to GitHub Actions every morning
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: 09:00
  
  # Check for updates to pip every morning
  - package-ecosystem: "pip"
    directory: /backend
    schedule: 
      interval: "daily"
      time: 09:00