services:
  jenkins:
    build:
      context: .
      dockerfile: /Docker/Docker-pylint-support/Dockerfile
    build:
      context: .
      dockerfile: /Docker/Docker-flask-app/Dockerfile
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home

